---
# tasks file for provision_ec2_instance

- name: Identify VPC/subnet to launch the subnet in
  include: get_instance_placement_details.yml

- name: Create/update security groups
  include: define_security_groups.yml

- name: Scale instances
  include: launch_instance.yml

- name: Assign elastic IPs
  include: assign_elastic_ips.yml
  when: instance.elastic_ips is defined

